kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodejs-deployment      #name of deployment
  namespace: nodejs
  labels:
    app: nodejs

spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs

  template:            #details of pod
    metadata:
      name: nodejs-dep-pod    #name of pod
      namespace: nodejs       #namespace in which I want to create the pod
      labels:
        app: nodejs

    spec:              #specs of our pod
      containers:
      - name: nodejs
        image: shamelsk/node-to-do-app:latest
        ports:
        - containerPort: 8000